# Generated by Django 2.2.2 on 2019-08-03 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('brand', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('nutrition_grade', models.CharField(max_length=1)),
                ('picture', models.URLField()),
                ('nutrition_image', models.URLField()),
                ('url', models.URLField()),
            ],
        ),
    ]
